name: Dependabot auto-merge

on:
  workflow_run:
    workflows:
      - Docker # CI を実行しているワークフローの名前を記載する
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    if: |
      github.actor == 'dependabot[bot]' &&
      github.event.workflow_run.conclusion == 'success'

    steps:

      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Order Dependabot to merge
        if: |
          ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr comment --body "@dependabot squash and merge" "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
